# Generated by Django 3.1.4 on 2021-03-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApps', '0002_loginmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginmodel',
            old_name='confirmPassword',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='loginmodel',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='loginmodel',
            old_name='lname',
            new_name='last_name',
        ),
    ]
