# Generated by Django 3.1.4 on 2021-03-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApps', '0003_auto_20210331_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='loginmodel',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='loginmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='loginmodel',
            name='last_name',
        ),
    ]
