# Generated by Django 3.1.4 on 2021-04-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApps', '0005_auto_20210402_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='confirm_password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
