# Generated by Django 3.1.5 on 2021-04-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApps', '0006_auto_20210402_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
